### ISSUE TITLE
PlatformError on Windows

### ISSUE THREAD

**Issue by Songtronix** [Aloxaf/silicon#5]
Command: ``cargo run -- main.rs -o test.png``
Output: ``thread 'main' panicked at '9: PlatformError', src\libcore\result.rs:1051:5``
BackTrace: 
``` 
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Program Files\Rust\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:384
   7: std::panicking::rust_begin_panic
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:311
   8: core::panicking::panic_fmt
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libcore\panicking.rs:85
   9: core::result::unwrap_failed<font_kit::error::GlyphLoadingError>
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\src\libcore\macros.rs:18
  10: core::result::Result<(), font_kit::error::GlyphLoadingError>::expect<(),font_kit::error::GlyphLoadingError>
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\src\libcore\result.rs:879
  11: silicon::font::PositionedGlyph::draw<closure>
             at .\src\font.rs:286
  12: silicon::font::FontCollection::draw_text_mut<image::dynimage::DynamicImage>
             at .\src\font.rs:253
  13: silicon::formatter::ImageFormatter::draw_line_number
             at .\src\formatter.rs:177
  14: silicon::formatter::ImageFormatter::format
             at .\src\formatter.rs:230
  15: silicon::run
             at .\src\main.rs:48
  16: silicon::main
             at .\src\main.rs:76
  17: std::rt::lang_start::{{closure}}<()>
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\src\libstd\rt.rs:64
  18: std::rt::lang_start_internal::{{closure}}
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\rt.rs:49
  19: std::panicking::try::do_call<closure,i32>
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:296
  20: panic_unwind::__rust_maybe_catch_panic
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libpanic_unwind\lib.rs:82
  21: std::panicking::try
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:275
  22: std::panic::catch_unwind
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panic.rs:394
  23: std::rt::lang_start_internal
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\rt.rs:48
  24: std::rt::lang_start<()>
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\src\libstd\rt.rs:64
  25: main
  26: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  27: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  28: BaseThreadInitThunk
  29: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\silicon.exe main.rs -o test.png` (exit code: 101)
```
After replacing all ``unwrap()``s I identified the following in ``src\font.rs:286`` as the problem:
```
self.font
            .rasterize_glyph(
                &mut canvas,
                self.id,
                self.size,
                &FontTransform::identity(),
                &origin,
                HintingOptions::None,
                RasterizationOptions::GrayscaleAa,
            )
            .expect("9");
```

**Comment by Aloxaf** [comment]
Thank you very much.

It seems like a tricky problem, I will give it a look tomorrow. (It's midnightl in China now

**Comment by Songtronix** [comment]
Issue got fixed with https://github.com/pcwalton/font-kit/commit/2fd68a8e932d43d498d58021d6fc78c0c0eef81f so I'll close the issue.
Just make sure to update once it is out 👍 
(and btw awesome thing you wrote here)

**Comment by Aloxaf** [comment]
Thank you so much!
