### ISSUE TITLE
[Error] : No package 'freetype2' found

### ISSUE THREAD

**Issue by byteshiva** [Aloxaf/silicon#62]
Failed to install (`cargo install silicon`) throws `No package 'freetype2' found`

```
$ cargo install silicon
```
```
--- stderr
configure: error: Package requirements (freetype2) were not met:

No package 'freetype2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** [makefile.cargo:83: /tmp/cargo-installKkTQ6y/release/build/servo-fontconfig-sys-0fe7df1e4d95efe8/out/Makefile] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").env("MAKEFLAGS",
                         env::var("CARGO_MAKEFLAGS").unwrap_or_default()).args(&["-R",
                                                                                 "-f",
                                                                                 "makefile.cargo"]).status().unwrap().success()', /home/xyz/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-4.0.9/build.rs:20:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `silicon v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installKkTQ6y`

Caused by:
  build failed
```

```
 uname -a
Linux  5.3.0-41-generic #33-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by byteshiva** [comment]
freetype2 error fixed by installing libfreetype6-dev,, but threw libxml2 error

$ sudo apt install libfreetype6-dev
```
--- stderr
configure: error: 
*** expat is required. or try to use --enable-libxml2
make: *** [makefile.cargo:83: /tmp/cargo-installK9FDUt/release/build/servo-fontconfig-sys-0fe7df1e4d95efe8/out/Makefile] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").env("MAKEFLAGS",
                         env::var("CARGO_MAKEFLAGS").unwrap_or_default()).args(&["-R",
                                                                                 "-f",
                                                                                 "makefile.cargo"]).status().unwrap().success()', /home/xyz/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-4.0.9/build.rs:20:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: std::panicking::begin_panic
  12: build_script_build::main
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  17: std::panicking::try
             at src/libstd/panicking.rs:270
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  20: main
  21: __libc_start_main
  22: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `silicon v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installK9FDUt`

Caused by:
  build failed

```

**Comment by byteshiva** [comment]
To make `silicon` work I had to install the below following packages.
```
sudo apt install expat
sudo apt install libxml2-dev
```


```
sudo apt install pkg-config libasound2-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb-composite0-dev
```

**Comment by byteshiva** [comment]
https://github.com/Aloxaf/silicon/pull/63
